### ISSUE TITLE
Could you provide some sample for the code?

### ISSUE THREAD

**Issue by HamsterCoderSim** [thesujitroy/Deep-neural-network-Transfer-learning-EEG-MEG-#1]
Thank you for your work and sharing, and it helps me a lot. But when I run the code, I don't know the shape of data. So I want to know what the format of the EEG and label is (such as the format of EEG is $channels x duration$)? It will be awesome if you can upload some data which you used.

**Comment by thesujitroy** [comment]
Sure, I will upload a sample data or you can download BCI comp Iv2b Data and load it in matlab. It will also work.
